// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/crossplaneio/crossplane-runtime/apis/core/v1alpha1"
	corev1 "k8s.io/api/core/v1"
)

// GetClassReference of this Instance.
func (mg *Instance) GetClassReference() *corev1.ObjectReference {
	return mg.Spec.ClassReference
}

// GetCondition of this Instance.
func (mg *Instance) GetCondition(ct runtimev1alpha1.ConditionType) runtimev1alpha1.Condition {
	return mg.Status.GetCondition(ct)
}

// SetClassReference of this Instance.
func (mg *Instance) SetClassReference(r *corev1.ObjectReference) {
	mg.Spec.ClassReference = r
}

// GetClassReference of this Lke.
func (mg *Lke) GetClassReference() *corev1.ObjectReference {
	return mg.Spec.ClassReference
}

// GetCondition of this Lke.
func (mg *Lke) GetCondition(ct runtimev1alpha1.ConditionType) runtimev1alpha1.Condition {
	return mg.Status.GetCondition(ct)
}

// SetClassReference of this Lke.
func (mg *Lke) SetClassReference(r *corev1.ObjectReference) {
	mg.Spec.ClassReference = r
}
